### ISSUE TITLE
Clean the preference panel to remove useless settings

### ISSUE THREAD

**Issue by rouvoy** [Apolline-Lille/apolline-android#47]
Remove all the settings that are not exploited by the Android App.

**Comment by kaal-dam** [comment]
duplicate #32 

the settings panel need a full rework, starting by using Android in app preference management
the issue #32 already discuss about what should be put as setting

**Comment by rouvoy** [comment]
Ok, #47 focuses on settings to be removed first, while #32 discusses new settings to be included.

**Comment by kaal-dam** [comment]
technically #32 discuss about both since the main goal of #32 is to allow user to use their own setting

some of actual setting was naturally removed because of the new ui of the app for example.
some new setting appeared because of coding decision.

it would be more effective to use only one issue to discuss both i think

**Comment by rouvoy** [comment]
Report from B. Hanoune: «_il faudrait nettoyer les settings: je pense que "chart types" est obsolète. c'est quoi auto-tracking ? temperature : pas affichée, mais c'est pas la peine de proposer en K. data atmo doit aussi être obsolète ?_»

**Comment by Sparow199** [comment]
Settings will be developed from scratsh soon.
